### ISSUE TITLE
Todo - Menu

### ISSUE THREAD

**Issue by Tricky1975** [PhantasarProductions/TFTRevamp#77]
This is also a bit of a checklist for me, as I want to do this right in "one go" as much as possible.
- [x] Left half status screen (only if that applies for the tab in question)
  - [x] Name Char
  - [x] HP
  - [x] AP
  - [x] Stats
  - [x] Equipment (also needed for #223)
- [x] Inventory screen
  - [x] Usable item - When selected used on the current character in the menu.
  - [x] Equipable items - When selected character will equip item if he/she can on the applicable spot
  - [x] Key items - Unusable. Your heroes will use the applicable item automatically when needed
- [ ] Item filter
  - [x] All items (any questions)
  - [x] Combat only (will be automatically used in combat, and not selectable in the field). Show only those items you can use in combat.
  - [x] Usable items (goes for field. Only use the items you can use on the field)
  - [ ] Equipable items (goes for field). Show only those item the current character can equip (Indeed when Jake is the current character, the stuff only Marrilona can equip will not be shown and vice versa).
    - [ ] Key items (show the key items only)
- [x] Abilities
  - [x] Show the abilities the character currently has
  - [x] Show "???" to the abilities the character does not yet have but show the requirements to unlock them or show "???" if a story event has to take place to make that happen first.
  - [x] Pagination
- [x] Configuration
  - [x] Joypad configuration #263
- [x] Quit game
  - [x] Are you sure? (Windows / Linux)
  - [x] Quit save? (Mac)

**Comment by Tricky1975** [comment]
I don’t see any more point to keep this open> It’s not exactly in the way I want this, but at least it works, and more alterings may destabalize this.
