### ISSUE TITLE
Combat command execution - checklist

### ISSUE THREAD

**Issue by Tricky1975** [PhantasarProductions/TFTRevamp#95]
# Performance as a whole
- [x] Show move + card of user
- [x] Fighter sprite animation (hero)
- [x] Fighter sprite animation (foe)
- [x] Perform action itself (see below)
- DROPPED: Counter (although this may be hard to set up well, so I need to work this out properly, or just drop it).
- [x] Create skill if applicable
- [x] Award skill points if applicable
- [x] Gain AP if applicable
- [x] Closure
# Action results
- [x] Accuracy check if needed. If it fails, byebye
- [x] Dodge check if needed. If it succeeds, byebye
- [ ] Dispell
- [x] Cure status changes (this always comes first) #260
- [x] Buffs / Debuffs
- [x] Recover HP or AP
- [x] Attack
- [x] Scripted stuff
- [x] Cause status changes (this always comes last)

**Comment by Tricky1975** [comment]
Attacking works, although the damage does not appear on screen. This will need to be sorted out later and has its own issue in #96

**Comment by Tricky1975** [comment]
Serves no more purpose.
